const path = require('path');

module.exports = {
    extends: ['tslint-react-hooks', 'tslint-config-prettier', 'tslint-jasmine-rules'],
    rules: {
        prettier: true,
        'array-type': [true, 'array-simple'],
        'arrow-return-shorthand': true,
        'ban-types': [
            true,
            ['Object', 'Avoid using the `Object` type. Did you mean `object`?'],
            ['Function', 'Avoid using the `Function` type. Prefer a specific function type, like `() => void`.'],
            ['Boolean', 'Avoid using the `Boolean` type. Did you mean `boolean`?'],
            ['Number', 'Avoid using the `Number` type. Did you mean `number`?'],
            ['String', 'Avoid using the `String` type. Did you mean `string`?'],
            ['Symbol', 'Avoid using the `Symbol` type. Did you mean `symbol`?'],
        ],
        'class-name': true,
        'comment-format': [true, 'check-space'],
        curly: true,
        forin: true,
        'jsdoc-format': true,
        'label-position': true,
        'max-line-length': [false, 140],
        'member-access': [true, 'no-public'],
        'no-angle-bracket-type-assertion': true,
        'no-arg': true,
        'no-bitwise': true,
        'no-conditional-assignment': true,
        'no-console': [true, 'debug', 'info', 'log', 'time', 'timeEnd', 'trace'],
        'no-construct': true,
        'no-debugger': true,
        'no-default-export': true,
        'no-duplicate-switch-case': true,
        'no-duplicate-super': true,
        'no-duplicate-variable': true,
        'no-inferrable-types': false,
        'no-empty': true,
        'no-eval': true,
        'no-misused-new': true,
        'no-parameter-properties': false,
        'no-reference': true,
        'no-require-imports': true,
        'no-shadowed-variable': true,
        'no-string-literal': false,
        'no-switch-case-fall-through': false,
        'no-unnecessary-initializer': true,
        'no-unsafe-finally': true,
        'no-unused-expression': false,
        'no-var-keyword': true,
        'no-var-requires': true,
        'one-variable-per-declaration': [true, 'ignore-for-loop'],
        'only-arrow-functions': [true, 'allow-declarations', 'allow-named-functions'],
        'ordered-imports': [
            true,
            {
                'import-sources-order': 'case-insensitive',
                'named-imports-order': 'case-insensitive',
            },
        ],
        'prefer-const': true,
        radix: true,
        'react-hooks-nesting': true,
        'switch-default': true,
        'triple-equals': [true, 'allow-null-check'],
        'unified-signatures': true,
        'use-isnan': true,
        'variable-name': [true, 'ban-keywords', 'check-format', 'allow-leading-underscore', 'allow-pascal-case'],
        'no-focused-tests': true,
    },
    jsRules: {
        'arrow-return-shorthand': true,
        'class-name': true,
        'comment-format': [true, 'check-space'],
        curly: true,
        forin: true,
        'jsdoc-format': true,
        'label-position': true,
        'max-line-length': [false, 140],
        'no-any': false,
        'no-arg': true,
        'no-bitwise': true,
        'no-conditional-assignment': true,
        'no-construct': true,
        'no-debugger': false,
        'no-default-export': true,
        'no-duplicate-switch-case': true,
        'no-duplicate-super': true,
        'no-duplicate-variable': true,
        'no-inferrable-types': false,
        'no-empty': true,
        'no-eval': true,
        'no-parameter-properties': false,
        'no-reference': true,
        'no-shadowed-variable': true,
        'no-string-literal': false,
        'no-switch-case-fall-through': false,
        'no-unnecessary-initializer': true,
        'no-unsafe-finally': true,
        'no-unused-expression': false,
        'no-use-before-declare': true,
        'no-var-keyword': true,
        'one-variable-per-declaration': [true, 'ignore-for-loop'],
        'only-arrow-functions': [true, 'allow-declarations', 'allow-named-functions'],
        'ordered-imports': [
            true,
            {
                'import-sources-order': 'case-insensitive',
                'named-imports-order': 'case-insensitive',
            },
        ],
        'prefer-const': true,
        radix: true,
        'switch-default': true,
        'triple-equals': [true, 'allow-null-check'],
        'use-isnan': true,
        'variable-name': [true, 'ban-keywords', 'check-format', 'allow-leading-underscore', 'allow-pascal-case'],
    },
    linterOptions: {},
    defaultSeverity: 'error',
    rulesDirectory: [path.join(path.dirname(require.resolve('tslint-plugin-prettier')), './')],
};
